name: "Bump Version"

on:
  push:
    branches:
      - "master"

jobs:
  bump-version:
    name: "Bump Version on master"
    runs-on: [self-hosted, docker-runner]

    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v3"
        with:
          ref: ${{ github.ref }}
      - name: "cat package.json"
        run: cat ./package.json
      - name: "Automated Version Bump"
        id: version-bump
        uses: "./.github/actions/sem-bump"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: "cat package.json"
        run: cat ./package.json
      - name: "Output Step"
        env:
          NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
        run: echo "new tag $NEW_TAG"
