name: "Bump Version"

on:
  pull_request:
    branches: ["master", "main"]

jobs:
  bump-version:
    name: "Bump Version on master "
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v3"
        with:
          ref: ${{ github.ref }}
      - name: Setup node
        uses: actions/setup-node@v3
      - name: "cat package.json"
        run: npm pkg get version
      # - name: "version bump"
      #   run: npm version major
      #   env:
      #     GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      #  log
      # logic check if pakcage.json version == self, reject on PR
      #
      # logic on push check for git branch tag apply bum p commit
      #
      - name: "Automated Version Bump"
        id: version-bump
        uses: "./.github/actions/sem-bump"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      # - name: "cat package.json"
      #   run: cat ./package.json
      # - name: "Output Step"
      #   env:
      #     NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
      #   run: echo "new tag $NEW_TAG"
